In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr=np.array(45)
print(arr)

45


In [4]:
import numpy as np
arr=np.array([11,23,12,34,54])
print(arr)

[11 23 12 34 54]


In [5]:
import numpy as np
arr=np.array([[11,22,33],[44,55,66]])
print(arr)

[[11 22 33]
 [44 55 66]]


In [6]:
import numpy as np
arr=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [9]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,4],[3,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 4]
  [3 5 6]]]


In [10]:
import numpy as np
a=np.array(45)
b=np.array([11,23,12,34,54])
c=np.array([[11,22,33],[44,55,66]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,4],[3,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [11]:
import numpy as np
arr=np.empty((5,5))
print(arr)

[[6.95324987e-310 6.95324986e-310 0.00000000e+000 0.00000000e+000
  1.41016814e-311]
 [4.94065646e-324 0.00000000e+000 0.00000000e+000 4.04738577e-320
  0.00000000e+000]
 [1.23022346e-321 1.41020393e-311 1.78022342e-306 1.05700345e-307
  0.00000000e+000]
 [1.41020393e-311 1.42410839e-306 7.56597770e-307 6.23059726e-307
  5.43472210e-322]
 [7.56599128e-307 1.78022206e-306 8.34451503e-308             nan
  2.56761491e-312]]


In [12]:
import numpy as np
arr=np.empty((3,2))
print(arr)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 4.24399158e-314]
 [6.36598737e-314 1.27319747e-313]]


In [13]:
import numpy as np
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
import numpy as np
arr=np.ones((4,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([3,5,7,2])
res=np.add(var1,var2)
print(res)

[ 4  7 10  6]


In [16]:
import numpy as np
var1=np.array([[1,4,2,6],[8,5,4,2]])
var2=np.array([[8,5,1,2],[6,9,0,4]])
res=np.add(var1,var2)
print(res)

[[ 9  9  3  8]
 [14 14  4  6]]


In [17]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([3,5,7,2])
res=np.subtract (var1,var2)
print(res)

[-2 -3 -4  2]


In [18]:
import numpy as np
var1=np.array([[1,4,2,6],[8,5,4,2]])
var2=np.array([[8,5,1,2],[6,9,0,4]])
res=np.subtract(var1,var2)
print(res)

[[-7 -1  1  4]
 [ 2 -4  4 -2]]


In [19]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([3,5,7,2])
res=np.multiply(var1,var2)
print(res)

[ 3 10 21  8]


In [20]:
import numpy as np
var1=np.array([[1,4,2,6],[8,5,4,2]])
var2=np.array([[8,5,1,2],[6,9,0,4]])
res=np.multiply(var1,var2)
print(res)

[[ 8 20  2 12]
 [48 45  0  8]]


In [22]:
import numpy as np
var1=np.array([4,12,3,4])
var2=np.array([2,4,3,2])
res=np.divide(var1,var2)
print(res)

[2. 3. 1. 2.]


In [24]:
import numpy as np
var1=np.array([4,10,8,4])
var2=np.array([1,5,7,2])
res=np.mod(var1,var2)
print(res)

[0 0 1 0]


In [26]:
import numpy as np
var1=np.array([2,2,3,4])
var2=np.array([5,6,7,2])
res=np.power(var1,var2)
print(res)

[  32   64 2187   16]


In [29]:
import numpy as np
var1=np.array([1,2,3,4])
res=np.reciprocal(var1)
print(res)

[1 0 0 0]


In [30]:
import numpy as np
var=np.array([1,2,3,4])
res=np.min(var)
print(res)

1


In [31]:
import numpy as np
var1=np.array([[1,2,3,4],[3,6,8,5]])
res=np.max(var1)
print(res)

8


In [32]:
import numpy as np
var=np.array([[12,4,2,5],[3,6,8,9]])
print(np.min(var),np.argmin(var))

2 2


In [33]:
import numpy as np
var=np.array([[12,4,2,5],[3,6,8,9]])
print(np.max(var),np.argmax(var))

12 0


In [34]:
import numpy as np
var=np.array([[81,9,36],[16,25,4]])
print(np.sqrt(var))

[[9. 3. 6.]
 [4. 5. 2.]]


In [35]:
import numpy as np
var=np.array([[81,9,36],[16,25,4]])
print(np.sin(var))

[[-0.62988799  0.41211849 -0.99177885]
 [-0.28790332 -0.13235175 -0.7568025 ]]


In [36]:
import numpy as np
var=np.array([[81,9,36],[16,25,4]])
print(np.cos(var))

[[ 0.77668598 -0.91113026 -0.12796369]
 [-0.95765948  0.99120281 -0.65364362]]


In [37]:
import numpy as np
var=np.array([[81,9,36],[16,25,4]])
print(np.tan(var))

[[-0.81099442 -0.45231566  7.75047091]
 [ 0.30063224 -0.13352641  1.15782128]]


In [40]:
import numpy as np
var=np.array([[81,9,36],[16,25,4]])
print(np.cumsum(var))

[ 81  90 126 142 167 171]


In [41]:
import numpy as np
arr = np.array([2,3,4,5])
print(arr[1],arr[3])

3 5


In [42]:
import numpy as np
arr = np.array([[2,3,4,5],[9,8,7,6]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 3


In [44]:
import numpy as np
arr = np.array([[2,3,4,5],[9,8,7,6]])
print(arr[0,-1])

5


In [45]:
import numpy as np
arr = np.array([9,8,7,6])
print(arr[-2])

7


In [46]:
import numpy as np
arr = np.array([9,8,7,6,5,4,3])
print(arr[1:5])

[8 7 6 5]


In [47]:
import numpy as np
arr = np.array([9,8,7,6,5,4,3])
print(arr[-4:-1])

[6 5 4]


In [48]:
import numpy as np
arr = np.array([9,8,7,6,5,4,3])
print(arr[1:5:2])

[8 6]


In [3]:
import numpy as np
arr = np.array([[9,8,7,6],[2,5,4,3]])
print(arr[0:2,2])

[7 4]


In [4]:
import numpy as np
arr = np.array([[9,8,7,6],[2,5,4,3]])
print(arr[0:2,1:3])

[[8 7]
 [5 4]]


In [6]:
import numpy as np
arr=np.array([22,33,44,55,66])
x=arr.copy()
arr[0] = 88
print(arr)
print(x)

[88 33 44 55 66]
[22 33 44 55 66]


In [7]:
import numpy as np
arr=np.array([22,33,44,55,66])
x=arr.view()
arr[0] = 88
print(arr)
print(x)

[88 33 44 55 66]
[88 33 44 55 66]


In [9]:
import numpy as np
arr = np.array([[1,2,3,4,5],[9,8,7,6,90]])
print(arr.shape)

(2, 5)


In [10]:
import numpy as np
arr=np.array([22,33,44,55,66],ndmin=5)
print(arr)
print('Shape of Array : ',arr.shape)

[[[[[22 33 44 55 66]]]]]
Shape of Array :  (1, 1, 1, 1, 5)


In [13]:
import numpy as np
arr = np.array([9,8,7,6,5,4,3,2])
newarr = arr.reshape(4,2)
print(newarr)

[[9 8]
 [7 6]
 [5 4]
 [3 2]]
